version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: teste@123
      MYSQL_DATABASE: integrationPHP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  php:
    image: php:7.4-apache
    container_name: php_server
    volumes:
      - ./seu_projeto:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: integrationPHP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
